server:
  port: 8002
spring:
  application:
    name: BQ-gateway

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
#    自动代理
    gateway:
      discovery:
        locator:
          enabled: true

#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 8
#        max-wait: 1ms






